service: photos-app-v2
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  # - serverless-webpack
  - serverless-bundle

useDotenv: true

# package:
#   individually: true

provider:
  name: aws
  runtime: nodejs14.x

environment:
  S3_BUCKET: ${env:S3_BUCKET}

functions:
  uploadPhoto:
    handler: src/handler.uploadPhoto
  uploadPhotos:
    handler: src/handler.uploadPhotos
  getPhotos:
    handler: src/handler.getPhotos
  getThumbnails:
    handler: src/handler.getThumbnails
  processImage:
    handler: src/handler.processImage

custom:
  bundle:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux sharp
