service: photos-app
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  # - serverless-webpack
  - serverless-bundle

useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x

environment:
  S3_BUCKET: ${env:S3_BUCKET}

functions:
  uploadPhoto:
    handler: src/handler.uploadPhoto
  getPhotos:
    handler: src/handler.getPhotos
  getThumbnails:
    handler: src/handler.getThumbnails

custom:
  bundle:
    packager: 'npm' # Packager that will be used to package your external modules
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux --libc=glibc sharp
